language: ruby
sudo: false
rvm:
- 2.4.2
cache: bundler
before_script:
- psql -c 'create role joy login createdb;' -U postgres
addons:
  postgresql: 9.6
  code_climate:
    repo_token: 8d0519230476d518ac697636d3ea539f19cb78d5d9a78a623f5abb2fc9ab5a50
script:
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rake db:seed
- bundle exec rake spec
- bundle exec rake rubocop
after_success:
- bundle exec codeclimate-test-reporter
